// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBQITXJsvSH4HmGdEIZ07hMcDGD_c9HSE',
    appId: '1:281929643074:android:f6291afb0e2746843c29db',
    messagingSenderId: '281929643074',
    projectId: 'chat-bot-c055c',
    databaseURL: 'https://chat-bot-c055c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-bot-c055c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiEM7Yf4JSE8foM7v2uD_txjXneqr0asg',
    appId: '1:281929643074:ios:aeb9308ddeca5fb53c29db',
    messagingSenderId: '281929643074',
    projectId: 'chat-bot-c055c',
    databaseURL: 'https://chat-bot-c055c-default-rtdb.firebaseio.com',
    storageBucket: 'chat-bot-c055c.appspot.com',
    iosBundleId: 'com.example.chatBot',
  );
}
